version: '3'
services:
  api:
    build: ./api/docker
    container_name: 'health_tree-api'
    command: /bin/sh -c "go run ./src/main.go" 
    stdin_open: true
    tty: true
    volumes:
      - ./api:/go/src/github.com/NUTMEG-hackathon/echo-tree-api
    ports:
      - 8888:8888
    depends_on:
       - "db"

  db:
    image: mysql:8.0
    container_name: 'health_tree-db'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./api/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  view:
    build: ./view
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./view/vue-project:/app/vue-project
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:8888

volumes:
  db-data:
    driver: local
