version: '3'
services:
  view:
    build: ./view
    container_name: 'health_tree-view'
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./view/vue-project:/app/vue-project
    stdin_open: true
    tty: true
  api:
    build: ./api
    container_name: 'health_tree-api'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
