FROM golang:1.13

WORKDIR /go/src/github.com/NUTMEG-hackathon/echo-tree-api

RUN go get -u github.com/go-sql-driver/mysql
RUN go get -u github.com/jinzhu/gorm
RUN go get -u github.com/labstack/echo
RUN go get -u github.com/labstack/echo/middleware
RUN go get -u github.com/dgrijalva/jwt-go
